[project]
name = "charla-api-quod-extract-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "logfire>=3.2.0",
    "pydantic-ai[logfire]>=0.0.19",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]
